version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vet_pos_system
      POSTGRES_USER: vet_pos_system_user
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
