services:
  - type: web
    name: vet-pos
    env: node
    plan: free
    branch: main
    buildCommand: |
      # Install PHP dependencies
      composer install --no-dev --optimize-autoloader
      
      # Build Angular frontend (in public folder)
      cd public
      npm install
      npm run build
      cd ..

      # Run Laravel optimizations
      php artisan key:generate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force || true
      php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://vet-pos.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: your-neon-host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: your-neon-database
      - key: DB_USERNAME
        value: your-neon-user
      - key: DB_PASSWORD
        value: your-neon-password
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: public
